[production]
prod-server ansible_host=${PROD_DEPLOY_HOST} ansible_user=${PROD_DEPLOY_USER} ansible_ssh_pass=${PROD_DEPLOY_PASSWORD}

[staging]
staging-server ansible_host=${STAGING_DEPLOY_HOST} ansible_user=${STAGING_DEPLOY_USER} ansible_ssh_pass=${STAGING_DEPLOY_PASSWORD}

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3