[production]
prod-server ansible_host=__PROD_DEPLOY_HOST__ ansible_user=__PROD_DEPLOY_USER__ ansible_ssh_pass=__PROD_DEPLOY_PASSWORD__

[staging]
staging-server ansible_host=__STAGING_DEPLOY_HOST__ ansible_user=__STAGING_DEPLOY_USER__ ansible_ssh_pass=__STAGING_DEPLOY_PASSWORD__

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3