[production]
__PROD_DEPLOY_HOST__

[staging]
__STAGING_DEPLOY_HOST__

# define variables for production group
[production:vars]
ansible_user=__PROD_DEPLOY_USER__
ansible_ssh_pass=__PROD_DEPLOY_PASSWORD__
china_service_path=__PROD_CHINA_SERVICE_PATH__
laos_service_path=__PROD_LAOS_SERVICE_PATH__
china_offshore_service_path=__PROD_CHINA_OFFSHORE_SERVICE_PATH__

# define variables for staging group
[staging:vars]
ansible_user=__STAGING_DEPLOY_USER__
ansible_ssh_pass=__STAGING_DEPLOY_PASSWORD__
china_service_path=__STAGING_CHINA_SERVICE_PATH__
laos_service_path=__STAGING_LAOS_SERVICE_PATH__
china_offshore_service_path=__STAGING_CHINA_OFFSHORE_SERVICE_PATH__

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3